image files

diff --git a/.github/workflows/sign-and-verify.yaml b/.github/workflows/sign-and-verify.yaml
--- a/.github/workflows/sign-and-verify.yaml
+++ b/.github/workflows/sign-and-verify.yaml
@@ -55,18 +55,50 @@ jobs:
         if: ${{ !inputs.is_docker_image }}
         run: echo "${{ secrets.PAT }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin
 
-      - name: Push artifact or Docker image and capture digest
+      - name: Debug environment variables
+        run: |
+          echo "is_docker_image=${{ inputs.is_docker_image }}"
+          echo "artifact_name=${{ inputs.artifact_name }}"
+          echo "artifact_path=${{ inputs.artifact_path }}"
+          echo "docker_image_ref=${{ inputs.docker_image_ref }}"
+          echo "IMAGE=$IMAGE"
+
+
+      - name: Push artifact and capture digest
         id: push
         run: |
+          echo "DEBUG: is_docker_image='${{ inputs.is_docker_image }}'"
+          echo "DEBUG: artifact_path='${{ inputs.artifact_path }}'"
+          echo "DEBUG: IMAGE='$IMAGE'"
+          
           if [[ "${{ inputs.is_docker_image }}" == "false" ]]; then
-            DIGEST=$(oras push "$IMAGE" ${{ inputs.artifact_path }}:application/octet-stream | tee /dev/stderr | grep -o 'sha256:[a-f0-9]\{64\}')
+            if [[ -z "${{ inputs.artifact_path }}" ]]; then
+              echo "ERROR: artifact_path is required when is_docker_image is false"
+              exit 1
+            fi
+          
+            DIGEST=$(oras push "$IMAGE" "${{ inputs.artifact_path }}":application/octet-stream | tee /dev/stderr | grep -o 'sha256:[a-f0-9]\{64\}')
           else
             docker push "$IMAGE"
             FULL_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE")
-            echo "Full digest: $FULL_DIGEST"
+            echo "DEBUG: Full digest: $FULL_DIGEST"
             DIGEST=${FULL_DIGEST#*@}
           fi
+          
           echo "digest=$DIGEST" >> $GITHUB_OUTPUT
+
+#      - name: Push artifact or Docker image and capture digest
+#        id: push
+#        run: |
+#          if [[ "${{ inputs.is_docker_image }}" == "false" ]]; then
+#            DIGEST=$(oras push "$IMAGE" ${{ inputs.artifact_path }}:application/octet-stream | tee /dev/stderr | grep -o 'sha256:[a-f0-9]\{64\}')
+#          else
+#            docker push "$IMAGE"
+#            FULL_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE")
+#            echo "Full digest: $FULL_DIGEST"
+#            DIGEST=${FULL_DIGEST#*@}
+#          fi
+#          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
 
       - name: Set image with digest
         run: echo "IMAGE_WITH_DIGEST=${IMAGE}@${{ steps.push.outputs.digest }}" >> $GITHUB_ENV
